# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Black events Scraper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '* */6 * * *' # 2시간마다

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git checkout HEAD^
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run script
      run: |
        python "main.py"
        
    - name: Commit
      run: |
        git config --local user.email "hammuu1112@gmail.com"
        git config --local user.name "Action bot"
        git add events.json
        git commit -m "[Auto] update event list"
        
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $
